# This file is part of SoSy-Lab Common,
# a library of useful utilities:
# https://github.com/sosy-lab/java-common-lib
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/java-common-lib"
  GH_REF: "github.com/sosy-lab/java-common-lib"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: 27593c42d5a732c69d4b99b74d66f7069aa27d00
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.7.1
